<MainWindow>
    BoxLayout:
        orientation: "vertical"
        Label:
            text: 'Main Window'
        Button:
            text: 'Start'
            on_press: print('start clicking'); root.setRunning(True)
        Button:
            text: 'Stop'
            on_press: print('stop clicking'); root.setRunning(False)
        Button:
            text: 'Settings'
            on_press: print('change on main window'); root.manager.current = 'settings'